run:
  tests: true
  skip-dirs:
    # regexp
    - test
    - vendor
    - .*/model
    - .*/cao
    - .*/dao
    - .*/repo
  modules-download-mode: vendor
  allow-parallel-runners: true

output:
  format: colored-line-number

linters-settings:
  goimports:
    local-prefixes: git.garena.com/shopee/insurance/insurance-backend/insurance-hub/
  stylecheck:
    initialisms: [""]
  revive:
    ignore-generated-header: true
    enable-all-rules: true
    rules:
      # modify arguments
      - name: add-constant
        arguments:
          - maxLitCount: "5"
            allowStrs: '""'
            allowInts: "0,1,2,8,10,16"
            allowFloats: "0.0,0.,1.0,1.,2.0,2.,10.0,10."
      - name: argument-limit
        arguments: [10]
      - name: cognitive-complexity
        arguments: [20]
      - name: function-length
        arguments: [40, 60]
      - name: function-result-limit
        arguments: [3]
      # disabled
      - name: banned-characters
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: exported
        disabled: true
      - name: file-header
        disabled: true
      - name: get-return
        disabled: true 
      - name: increment-decrement
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: package-comments
        disabled: true
      - name: unused-receiver
        disabled: true
      - name: var-naming
        disabled: true

linters:
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - errorlint
    - gocognit
    - goconst
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - makezero
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  max-issues-per-linter: 0
#  new: true
#  new-from-rev: HEAD~
#  whole-files: true

severity:
  # ignore info warning error
  default-severity: info
  rules:
    - linters:
      - bodyclose
      - deadcode
      - durationcheck
      - errcheck
      - govet
      severity: error
