// generated by deep-copy --type Schematyper --skip ID,MultipleOf --pointer-receiver -o ./copy_schema_typer.go .; DO NOT EDIT.

package gen

// DeepCopy generates a deep copy of *Schematyper
func (o *Schematyper) DeepCopy() *Schematyper {
	var cp Schematyper = *o
	return &cp
}
