// Code generated by "go-enum -type=Gender"; DO NOT EDIT.

// Install go-enum by `go get -u github.com/searKing/golang/tools/go-enum`
package gen

import (
	"database/sql"
	"database/sql/driver"
	"encoding"
	"encoding/json"
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-1]
	_ = x[Male-2]
	_ = x[Female-3]
}

const _Gender_name = "UnknownMaleFemale"

var _Gender_index = [...]uint8{0, 7, 11, 17}

func _() {
	var _nil_Gender_value = func() (val Gender) { return }()

	// An "cannot convert Gender literal (type Gender) to type fmt.Stringer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ fmt.Stringer = _nil_Gender_value
}

func (i Gender) String() string {
	i -= 1
	if i >= Gender(len(_Gender_index)-1) {
		return "Gender(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Gender_name[_Gender_index[i]:_Gender_index[i+1]]
}

// New returns a pointer to a new addr filled with the Gender value passed in.
func (i Gender) New() *Gender {
	clone := i
	return &clone
}

var _Gender_values = []Gender{1, 2, 3}

var _Gender_name_to_values = map[string]Gender{
	_Gender_name[0:7]:   1,
	_Gender_name[7:11]:  2,
	_Gender_name[11:17]: 3,
}

// ParseGenderString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ParseGenderString(s string) (Gender, error) {
	if val, ok := _Gender_name_to_values[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Gender values", s)
}

// GenderValues returns all values of the enum
func GenderValues() []Gender {
	return _Gender_values
}

// IsAGender returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Gender) Registered() bool {
	for _, v := range _Gender_values {
		if i == v {
			return true
		}
	}
	return false
}

func _() {
	var _nil_Gender_value = func() (val Gender) { return }()

	// An "cannot convert Gender literal (type Gender) to type encoding.BinaryMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryMarshaler = &_nil_Gender_value

	// An "cannot convert Gender literal (type Gender) to type encoding.BinaryUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryUnmarshaler = &_nil_Gender_value
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for Gender
func (i Gender) MarshalBinary() (data []byte, err error) {
	return []byte(i.String()), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for Gender
func (i *Gender) UnmarshalBinary(data []byte) error {
	var err error
	*i, err = ParseGenderString(string(data))
	return err
}

func _() {
	var _nil_Gender_value = func() (val Gender) { return }()

	// An "cannot convert Gender literal (type Gender) to type json.Marshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Marshaler = _nil_Gender_value

	// An "cannot convert Gender literal (type Gender) to type encoding.Unmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Unmarshaler = &_nil_Gender_value
}

// MarshalJSON implements the json.Marshaler interface for Gender
func (i Gender) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Gender
func (i *Gender) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Gender should be a string, got %s", data)
	}

	var err error
	*i, err = ParseGenderString(s)
	return err
}

func _() {
	var _nil_Gender_value = func() (val Gender) { return }()

	// An "cannot convert Gender literal (type Gender) to type encoding.TextMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextMarshaler = _nil_Gender_value

	// An "cannot convert Gender literal (type Gender) to type encoding.TextUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextUnmarshaler = &_nil_Gender_value
}

// MarshalText implements the encoding.TextMarshaler interface for Gender
func (i Gender) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Gender
func (i *Gender) UnmarshalText(text []byte) error {
	var err error
	*i, err = ParseGenderString(string(text))
	return err
}

//func _() {
//	var _nil_Gender_value = func() (val Gender) { return }()
//
//	// An "cannot convert Gender literal (type Gender) to type yaml.Marshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Marshaler = _nil_Gender_value
//
//	// An "cannot convert Gender literal (type Gender) to type yaml.Unmarshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Unmarshaler = &_nil_Gender_value
//}

// MarshalYAML implements a YAML Marshaler for Gender
func (i Gender) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Gender
func (i *Gender) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ParseGenderString(s)
	return err
}

func _() {
	var _nil_Gender_value = func() (val Gender) { return }()

	// An "cannot convert Gender literal (type Gender) to type driver.Valuer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ driver.Valuer = _nil_Gender_value

	// An "cannot convert Gender literal (type Gender) to type sql.Scanner" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ sql.Scanner = &_nil_Gender_value
}

func (i Gender) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Gender) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := ParseGenderString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

// GenderSliceContains reports whether sunEnums is within enums.
func GenderSliceContains(enums []Gender, sunEnums ...Gender) bool {
	var seenEnums = map[Gender]bool{}
	for _, e := range sunEnums {
		seenEnums[e] = false
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			seenEnums[v] = true
		}
	}

	for _, seen := range seenEnums {
		if !seen {
			return false
		}
	}

	return true
}

// GenderSliceContainsAny reports whether any sunEnum is within enums.
func GenderSliceContainsAny(enums []Gender, sunEnums ...Gender) bool {
	var seenEnums = map[Gender]struct{}{}
	for _, e := range sunEnums {
		seenEnums[e] = struct{}{}
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			return true
		}
	}

	return false
}
