package gen

// generated by "schematyper -o schema_type.go --package gen ./schematyper.json" -- DO NOT EDIT

type PositiveInteger int

// Core schema meta-schema
type Schematyper struct {
	ExclusiveMaximum bool    `json:"exclusiveMaximum,omitempty"`
	ExclusiveMinimum bool    `json:"exclusiveMinimum,omitempty"`
	ID               string  `json:"id,omitempty"`
	Maximum          float64 `json:"maximum,omitempty"`
	Minimum          float64 `json:"minimum,omitempty"`
	MultipleOf       float64 `json:"multipleOf,omitempty"`
}

type SimpleTypes interface{}

type StringArray []StringArrayItem

type StringArrayItem string
